import Head from "next/head";
import Header from "@/components/Header";
import Container from "react-bootstrap/Container";
import Footer from "@/components/Footer";
import {Tbl} from "@/components/Tbl";
import AppGuides from "@/components/AppGuides";

export default function Home() {
  return (
    <>
      <Head>
        <title>GPU Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
                {/* <link rel="icon" href="../public/favicon.ico" /> */}
        {/* <link rel="icon" href="server.png"></link> */}
        {/* <link rel="shortcut icon" href="../public/favicon.ico"></link> */}
      </Head>
      <Container as="main" className="py-4 px-3 mx-auto">
        <Header />

        <AppGuides />
        

        < Tbl />

        
        <Footer />
        
      </Container>
    </>
  );
}
